### ISSUE TITLE
Volume attachments fail when Quorum is disabled past version 0.13.1

### ISSUE THREAD

**Issue by tw185112** [piraeusdatastore/linstor-csi#155] opened 2022-03-16 12:25 UTC
Expected/Previous behaviour: 
- Our setup:
	- Linstor Cluster with Quorum feature disabled.
	- Cluster is running on the edge and is limited to 2 diskful nodes. This cannot be changed as it is a limitation in our product.
	- Redundant pair of servers.
- We are using Piraeus to provide storage to Kubernetes cluster where nodes are running diskless
- Version 0.11.0 was working fine:
	- When one of the two diskful nodes was offline, we create a pod which mounts a Persistent Volume stored in Linstor,
		the volume is attached successfully and storage can be accessed in the volume.
		When the failed diskful node is restored, DRBD restores the storage. We have accepted the risk of split brain and have
		mitigations for this.
- Resource group (Kubernetes) in Linstor define place count as 2.

Current/Observed behaviour:
- Volume attachment no longer succeeds when updated to 0.13.1 version.
- The following 404 error is produced from the csi-controller - `msg="method failed" func="github.com/sirupsen/logrus.(*Entry).Error" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:297" error="rpc error: code = Internal desc = ControllerPublishVolume failed for pvc-fa6e974e-1eee-4750-af4e-20c06a01e5e5: 404 Not Found"`
- The Linstor-plugin  produces the error (quorum error) - `msg="1 replicas of 2 are apparently not reachable, create a new diskfull resource for quorum"`
- This is unexpected because we are running with quorum disabled.
- Upon further investigation, we believe this error is caused by the [this line ](https://github.com/piraeusdatastore/linstor-csi/blob/v0.13.1/pkg/client/linstor.go#L471) in the Linstor-CSI code.

We would be happy to collab to find a solution for this issue.
Potential options we have identified:
- Return to original behaviour (regression possible for other situations).
- Insert a way to turn off that check, if the controller is configured to run with quorum disabled i.e. to skip these checks
- Alternatively, use a config map to configure to run in a quorum free mode, so skip quorum checks. (Configuration of the pod is changed).

We have rolled back to 0.11.0 for now but would like to fix to move forward with updates in the future.

**Comment by WanzenBug** [comment] 2022-03-16 14:41
Thanks for the detailed explanation and investigation. This is definitly unexpected behaviour, mostly because we _strongly_ encourage everyone to use quorum whenever possible.

As an aside, you can still get quorum with just two diskful nodes and an automatically created "diskless" tiebreaker. I obviously don't know enough about your set up, but if you accept the cost of an automatic diskless resource for every volume, you can have quorum enabled without issues.

I think you have already laid out all the available options:

> Return to original behaviour (regression possible for other situations).

There is specific situation this check tries to work around, explained in a comment a bit further up, and I'd hesitate to change that back. I'm not particularly happy with this special casing, but it was the best we could come up with.

> Insert a way to turn off that check, if the controller is configured to run with quorum disabled i.e. to skip these checks

That is my preferred solution. A simple check on the resource definition for `DrbdOptions/Resource/quorum` should be good enough.

> Alternatively, use a config map to configure to run in a quorum free mode, so skip quorum checks. (Configuration of the pod is changed).

Not a fan of this option, as it sets an option for the whole cluster that might only be needed for a specific storage class or similar

**Comment by tw185112** [comment] 2022-03-17 09:32
Thanks for your quick response on this issue. 

We would be happy to move forward with that second option laid out. How would you like to proceed with this? We can contribute code changes for this but how would you like us to supply those changes? Also would be open to liaise with yourself on the best way to implement this.

I would also like to verify that quorum can be set at the controller, resource group and resource levels. Is our understanding on this correct?

We are looking into the diskless solution you mentioned but at this point in time it is not something we can implement unfortunately.

**Comment by WanzenBug** [comment] 2022-03-17 10:27
> How would you like to proceed with this?

I'm open to review a pull request. Some general guidance on what I would implement:

* Have a new `useQuorum bool` parameter on [`Attach()`](https://github.com/piraeusdatastore/linstor-csi/blob/master/pkg/client/linstor.go#L427)
* use that parameter in the `shouldCreateDiskful` condition: https://github.com/piraeusdatastore/linstor-csi/blob/master/pkg/client/linstor.go#L492
* Add a new `UseQuorum` field to [`volume.Info`](https://github.com/piraeusdatastore/linstor-csi/blob/master/pkg/volume/volume.go#L30)
* In [`resourceDefinitionToVolume()`](https://github.com/piraeusdatastore/linstor-csi/blob/master/pkg/client/linstor.go#L209) check if the `DrbdOptions/Resource/quorum` property is set to something other than `disabled` (if not set -> no quorum) and fill the info struct as need.

Then you just have to fill in the collected information at the appropriate call sites.

> I would also like to verify that quorum can be set at the controller, resource group and resource levels. Is our understanding on this correct?

As far as I know: yes, that is correct.

**Comment by tw185112** [comment] 2022-05-12 09:08
Hi @WanzenBug , 

I have wrote the code up for this fix but I am a little unsure on how to proceed creating a pull request for to you review. How do I go about creating a branch in this repo, and which branch would be best to be basing off in the pull request?

Thanks in advance

**Comment by WanzenBug** [comment] 2022-05-12 09:22
Standard procedure would be:

* Fork the repository
* Commit your changes (use `git commit --signoff` to comply with CNCF guidelines)
* Push to your fork
* Create a PR from your fork to the master branch in this repo.

**Comment by WanzenBug** [comment] 2022-06-03 08:10
I think the issue is resolved, and a new version was released, so I'm closing this issue

**Closed by WanzenBug** 2022-06-03 08:10 UTC
